spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev

  application:
    name: freelance-demo

  datasource:
    url: jdbc:mysql://localhost:3306/freelance_management_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT}

logging:
  level:
    root: INFO
    com.example.freelance_demo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    persist-authorization: true
    try-it-out-enabled: true
    default-produces-media-type: application/json
